# Generated by Django 4.2.16 on 2024-09-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restaurant_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("country_code", models.IntegerField()),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("locality", models.CharField(max_length=255)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                ("cuisines", models.CharField(max_length=255)),
                (
                    "average_cost_for_two",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("currency", models.CharField(max_length=50)),
                ("has_table_booking", models.BooleanField()),
                ("has_online_delivery", models.BooleanField()),
                ("is_delivering_now", models.BooleanField()),
                ("switch_to_order_menu", models.BooleanField()),
                ("price_range", models.IntegerField()),
                ("aggregate_rating", models.FloatField()),
                ("rating_color", models.CharField(max_length=50)),
                ("rating_text", models.CharField(max_length=50)),
                ("votes", models.IntegerField()),
            ],
        ),
    ]
